use std::fmt::{Display, Formatter};

#[derive(Debug, PartialEq, Clone)]
pub enum Token<'src> {
    LiteralInt(i64),
    LiteralFloat(f64),
    LiteralBool(bool),
    LiteralString(&'src str),
    Identifier(&'src str),
    Operator(char),
    Comma,
    Dot,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    DoubleStar,
    DoubleEqual,
    LessThanEqual,
    GreaterThanEqual,
    NotEqual,
    DoubleSlash,
    PlusEqual,
    MinusEqual,
    StarEqual,
    DoubleStarEqual,
    SlashEqual,
    PercentEqual,
    DoubleSlashEqual,
    Colon,
    If,
    Else,
    For,
    While,
    Do,
    Then,
    End,
    Loop,
    Let,
    Mut,
    Fn,
    Return,
    Class,
}

impl Display for Token<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Token::LiteralInt(int) => write!(f, "{}", int),
            Token::LiteralString(string) => write!(f, "{}", string),
            Token::LiteralBool(true) => write!(f, "true"),
            Token::LiteralBool(false) => write!(f, "false"),
            Token::LiteralFloat(float) => write!(f, "{}", float),
            Token::Identifier(ident) => write!(f, "{}", ident),
            Token::Operator(c) => write!(f, "{}", c),
            Token::Comma => write!(f, ","),
            Token::Dot => write!(f, "."),
            Token::LeftParen => write!(f, "("),
            Token::RightParen => write!(f, ")"),
            Token::LeftBrace => write!(f, "{{"),
            Token::RightBrace => write!(f, "}}"),
            Token::DoubleStar => write!(f, "**"),
            Token::DoubleEqual => write!(f, "=="),
            Token::LessThanEqual => write!(f, "<="),
            Token::GreaterThanEqual => write!(f, ">="),
            Token::NotEqual => write!(f, "!="),
            Token::DoubleSlash => write!(f, "//"),
            Token::PlusEqual => write!(f, "+="),
            Token::MinusEqual => write!(f, "-="),
            Token::StarEqual => write!(f, "*="),
            Token::DoubleStarEqual => write!(f, "**="),
            Token::SlashEqual => write!(f, "/="),
            Token::PercentEqual => write!(f, "%="),
            Token::DoubleSlashEqual => write!(f, "//="),
            Token::Colon => write!(f, ":"),
            Token::If => write!(f, "if"),
            Token::Else => write!(f, "else"),
            Token::For => write!(f, "for"),
            Token::While => write!(f, "while"),
            Token::Do => write!(f, "do"),
            Token::Then => write!(f, "then"),
            Token::End => write!(f, "end"),
            Token::Loop => write!(f, "loop"),
            Token::Let => write!(f, "let"),
            Token::Mut => write!(f, "mut"),
            Token::Fn => write!(f, "fn"),
            Token::Return => write!(f, "return"),
            Token::Class => write!(f, "class"),
        }
    }
}
