[package]
name = "proglang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.3.0"
chumsky = { git = "https://github.com/zesterer/chumsky.git" }
clap = "4.3.5"
clap_derive = "4.3.2"
