use crate::syntax::span::Spanned;
use std::fmt::{Display, Formatter};

#[derive(Debug)]
pub enum TokenTree<'src> {
    Tree(Vec<TokenTree<'src>>),
    Leaf(Spanned<Token<'src>>),
}

#[derive(Debug, PartialEq, Clone)]
pub enum Token<'src> {
    LiteralInt(i64),
    LiteralFloat(f64),
    LiteralBool(bool),
    LiteralString(&'src str),
    Identifier(&'src str),
    Operator(char),
    Comma,
    StatementEnd,
    LeftParen,
    RightParen,
    DoubleStar,
    DoubleEqual,
    LessThanEqual,
    GreaterThanEqual,
    NotEqual,
    DoubleSlash,
    PlusEqual,
    MinusEqual,
    StarEqual,
    DoubleStarEqual,
    SlashEqual,
    PercentEqual,
    DoubleSlashEqual,
    Arrow,
    If,
    For,
    While,
    Do,
    Fn,
    Return,
    Pub,
    Prot,
    Priv,
    Class,
    Interface,
    Import,
    BlockStart,
    BlockEnd,
}

impl<'src> Display for Token<'src> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Token::LiteralInt(int) => write!(f, "{}", int),
            Token::LiteralString(string) => write!(f, "{}", string),
            Token::LiteralBool(true) => write!(f, "true"),
            Token::LiteralBool(false) => write!(f, "false"),
            Token::LiteralFloat(float) => write!(f, "{}", float),
            Token::Identifier(ident) => write!(f, "{}", ident),
            Token::Operator(c) => write!(f, "{}", c),
            Token::Comma => write!(f, ","),
            Token::LeftParen => write!(f, "("),
            Token::RightParen => write!(f, ")"),
            Token::DoubleStar => write!(f, "**"),
            Token::DoubleEqual => write!(f, "=="),
            Token::LessThanEqual => write!(f, "<="),
            Token::GreaterThanEqual => write!(f, ">="),
            Token::NotEqual => write!(f, "!="),
            Token::DoubleSlash => write!(f, "//"),
            Token::PlusEqual => write!(f, "+="),
            Token::MinusEqual => write!(f, "-="),
            Token::StarEqual => write!(f, "*="),
            Token::DoubleStarEqual => write!(f, "**="),
            Token::SlashEqual => write!(f, "/="),
            Token::PercentEqual => write!(f, "%="),
            Token::DoubleSlashEqual => write!(f, "//="),
            Token::Arrow => write!(f, "->"),
            Token::If => write!(f, "if"),
            Token::For => write!(f, "for"),
            Token::While => write!(f, "while"),
            Token::Do => write!(f, "do"),
            Token::StatementEnd => write!(f, "end of statement"),
            Token::Fn => write!(f, "fn"),
            Token::Return => write!(f, "return"),
            Token::Pub => write!(f, "pub"),
            Token::Prot => write!(f, "prot"),
            Token::Priv => write!(f, "priv"),
            Token::Class => write!(f, "class"),
            Token::Interface => write!(f, "interface"),
            Token::Import => write!(f, "import"),
            // TODO: make sure there's no quotes around these in the error reporting
            Token::BlockStart => write!(f, "start of block"),
            Token::BlockEnd => write!(f, "end of block"),
        }
    }
}
